try built in tf fmt

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -11,17 +11,27 @@ jobs:
       - name: Install Terraform
         uses: hashicorp/setup-terraform@v2
 
-      - name: Lint
-        uses: dflook/terraform-fmt-check@v1
-        id: tf-lint-result
-        with:
-          path: ${{ github.workspace }}/terraform/stacks/
+      #- name: Lint
+      #  uses: dflook/terraform-fmt-check@v1
+      #  id: tf-lint-result
+      #  with:
+      #    path: ${{ github.workspace }}/terraform/stacks/
 
+      #- name: Check Lint Result
+      #  if: ${{ failure() && steps.tf-lint-result.outputs.failure-reason == 'check-failed' }}
+      #  run: | 
+      #    echo "Terraform formatting check failed"
+      #    exit 1
+
+      -name: Lint
+        run: |
+          cd ${{ github.workspace }}/terraform/stacks/dash-endpoints/
+          terraform fmt --recursive
+      
       - name: Check Lint Result
-        if: ${{ failure() && steps.tf-lint-result.outputs.failure-reason == 'check-failed' }}
-        run: | 
+        if: ${{ failure() }}
           echo "Terraform formatting check failed"
-          exit 1      
+          exit 1
 
       - name: Setup Terraform Workspace
         run: |
